name = "Niggacraft"
author = "oiipo"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2cde938650deb84216a06d7cb4fffd060864fd5d64611a2269ef082df67dafd"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
