name = "Niggacraft"
author = "oiipo"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "460fb1993e02f2b4e8ba86557a1e8e66ca64038032a5e68aae3d957f8a1657df"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
